export default {
    power_lucien: "Ce pouvoir ne fait rien.",
    power_phone: "+30% sur vos gains et pertes en gold.<br/>N'inclus pas l'achat de pouvoirs.",
    power_fox: "Vous donne un pouvoir aleatoire",
    power_deserterJack: "Vous debutez avec une piece aléatoire en moins.",
    power_monkeys: "Vos deux pieces avec le moins de points disparaissent.",
    power_mirror: "Les points sur le board sont inversé <br/> ( que pour vous).",
    power_steve: "Vous commencez en premier.",
    power_pact: "Au debut du round, vous et votre adversaire ajoutez une piece de votre choix sur le board.",
    power_watch: "Vos points maximum pour knocker augmentent de 10.<br/>Bonus de knock de 10 gold.",
    power_chimist: "Vous pouvez aligner les pieces en diagonal.<br/>Vous recuperez les 4 plus grosses pieces non aligné de l'ennemi.",
    power_fog: "Votre adversaire ne connnait pas les autres pouvoirs que vous choisissez.",
    power_curse: "Votre adversaire est forcé de choisir Lucien<br/>Il ne depense pas les gold de son choix initial",
    power_final: "Vous pouvez knocker sans minimum de points.",
    power_karen: "Les pieces sont redistribués, pour tout le monde.",
    power_eye: "Vous voyez toute les piece de l'adversaire (apres war pact) <br/>Vos points sont doublés.",
    power_unknow: "whoever read this love adolph hitler",

    draw: "Draw",
    win: "You won",
    he_capitulate: "He capitulated",
    lost: "You lost",
    you_capitulate: "You capitulated",
    capitulate: "Capitulate",
    back_lobby: "Back to lobby",
    revenge: "Revenge",
    playbot: "Play against computer",
    you_challenge: "You challenged",
    he_challenge: "challenged you !",
    accept: "accept",
    decline: "decline",
    cancel: "cancel",
    online: "online",
    ingame: "in game",
    challenging: "challenging",
    greenPiece : "Green piece",
    randomPiece : "Random piece",
    nextRound : "Next round",

    name: "username",
    password: "password",
    login: "login",
    newAccount: "new account",
    userEmpty: "username is empty",
    userAlphaNum: "username must contain only letter and num",
    userTooLong: "username is too long",
    passEmpty: "password field is empty",

    youFull : "You made FULL and won",
    heFull : "The Scum made FULL and won",
    youKnockWith : "You knocked with",
    heKnockWith : "The scum knocked with",
    youAreWinning : "You won",
    heIsWinning : "He won",
    youKnock : "You knocked",
    heKnock : "The scum Knocked",
    with : "with", 
    heCounter : "The scum counter knocked and won",
    youCounter : "You counter knocked and won",
    youPick : "Pick an empty case",
    hePick : "Is is scum turn to pick an empty case",
    pickPower : "Pick a power",
    youPlay : "Jouer play",
    first : "first",
    second : "second",
    waitPower : "scum is picking power",
    waitPower2 : "he is taking so much time...",
    infoPickGreen : "Pick the green piece",
    infoPickRandom : "or pick random piece",
    opTurn : "It is scum turn to play",
    discardBlue : "Discard a blue piece",
    orKnockFor : "..Or knock for",
    opTurnDiscard1 : "it is scum turn",
    opTurnDiscard2 : "to discard a piece",
    rules : "Rule of the game",
}