export default {
     power_lucien: "Ce pouvoir ne fait rien.",
     power_phone: "+30% sur vos gains et pertes en gold.<br/>N'inclus pas l'achat de pouvoirs.",
     power_fox: "Vous donne un pouvoir aleatoire",
     power_deserterJack: "Vous debutez avec une piece aléatoire en moins.",
     power_monkeys: "Vos deux pieces avec le moins de points disparaissent.",
     power_mirror: "Les points sur le board sont inversé <br/> ( que pour vous).",
     power_steve: "Vous commencez en premier.",
     power_pact: "Au debut du round, vous et votre adversaire ajoutez une piece de votre choix sur le board.",
     power_watch: "Vos points maximum pour knocker augmentent de 10.<br/>Bonus de knock de 10 gold.",
     power_chimist: "Vous pouvez aligner les pieces en diagonal.<br/>Vous recuperez les 4 plus grosses pieces non aligné de l'ennemi.",
     power_fog: "Votre adversaire ne connnait pas les autres pouvoirs que vous choisissez.",
     power_curse: "Votre adversaire est forcé de choisir Lucien<br/>Il ne depense pas les gold de son choix initial",
     power_final: "Vous pouvez knocker sans minimum de points.",
     power_karen: "Les pieces sont redistribués, pour tout le monde.",
     power_eye: "Vous voyez toute les piece de l'adversaire (apres war pact) <br/>Vos points sont doublés.",
     power_unknow: "whoever read this love adolph hitler",
}