declare const _default: {
    fr: {
        power_lucien: string;
        power_phone: string;
        power_fox: string;
        power_deserterJack: string;
        power_monkeys: string;
        power_mirror: string;
        power_steve: string;
        power_pact: string;
        power_watch: string;
        power_chimist: string;
        power_fog: string;
        power_curse: string;
        power_final: string;
        power_karen: string;
        power_eye: string;
        power_unknow: string;
        capitulate: string;
        back_lobby: string;
        revenge: string;
        playbot: string;
        you_challenge: string;
        he_challenge: string;
        accept: string;
        decline: string;
        cancel: string;
        online: string;
        ingame: string;
        challenging: string;
        name: string;
        password: string;
        login: string;
        newAccount: string;
        userEmpty: string;
        userAlphaNum: string;
        userTooLong: string;
        passEmpty: string;
    };
};
export default _default;
//# sourceMappingURL=index.d.ts.map