version: "3.9"
services:
  
  back:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    restart: always
  
  mongo:
    image: mongo:latest
    env_file:
     - ./back/.env
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports: 
      - 8081:8081
    env_file:
     - .meenv

volumes:
  mongodb_data_container: