"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.powers = void 0;
exports.powers = {
    lucien: {
        id: "lucien",
        name: "Lucien",
        description: "Ce pouvoir ne fait rien.",
        image: "lucien.jpg",
        cost: 0,
        max: 3,
    },
    phone: {
        id: "phone",
        name: "Gramophone",
        description: "+30% sur vos gains et pertes en gold.<br/>N'inclus pas l'achat de pouvoirs.",
        image: "phone.jpg",
        cost: 4,
        max: 3,
    },
    fox: {
        id: "fox",
        name: "Jackson Gambler",
        description: "Vous donne un pouvoir aleatoire",
        image: "fox.jpg",
        cost: 5,
        max: 3,
    },
    deserterJack: {
        id: "deserterJack",
        name: "Deserter Jack",
        description: "Vous debutez avec une piece aléatoire en moins.",
        image: "leave.jpg",
        cost: 8,
        max: 3,
    },
    monkeys: {
        id: "monkeys",
        name: "Smart monkeys",
        description: "Vos deux pieces avec le moins de points disparaissent.",
        image: "monkeys.jpg",
        cost: 11,
        max: 3,
    },
    mirror: {
        id: "mirror",
        name: "Mirror of Darkness",
        description: "Les points sur le board sont inversé <br/> ( que pour vous).",
        image: "mirror.jpg",
        cost: 7,
        max: 1,
    },
    steve: {
        id: "steve",
        name: "Hurry Steve",
        description: "Vous commencez en premier.",
        image: "first.jpg",
        cost: 9,
        max: 3,
    },
    pact: {
        id: "pact",
        name: "War pact",
        description: "Au debut du round, vous et votre adversaire ajoutez une piece de votre choix sur le board.",
        image: "pact.jpg",
        cost: 5,
        max: 3,
    },
    watch: {
        id: "watch",
        name: "Early Fang",
        description: "Vos points maximum pour knocker augmentent de 10.<br/>Bonus de knock de 10 gold.",
        image: "watch.jpg",
        cost: 10,
        max: 3,
    },
    chimist: {
        id: "chimist",
        name: "Stacy Chemistry",
        description: "Vous pouvez aligner les pieces en diagonal.<br/>Vous recuperez les 4 plus grosses pieces non aligné de l'ennemi.",
        image: "chimist.jpg",
        cost: 18,
        max: 1,
    },
    fog: {
        id: "fog",
        name: "Fog of war",
        description: "Votre adversaire ne connnait pas les autres pouvoirs que vous choisissez.",
        image: "fog.jpg",
        cost: 16,
        max: 1,
    },
    curse: {
        id: "curse",
        name: "Emma Curse",
        description: "Votre adversaire est forcé de choisir Lucien<br/>Il ne depense pas les gold de son choix initial",
        image: "curse.jpg",
        cost: 16,
        max: 3,
    },
    final: {
        id: "final",
        name: "Let's do it",
        description: "Vous pouvez knocker sans minimum de points.",
        image: "final.jpg",
        cost: 32,
        max: 1,
    },
    karen: {
        id: "karen",
        name: "Complain Karen",
        description: "Les pieces sont redistribués, pour tout le monde.",
        image: "karen.jpg",
        cost: 30,
        max: 1,
    },
    eye: {
        id: "eye",
        name: "Eye of the god",
        description: "Vous voyez toute les piece de l'adversaire (apres war pact) <br/>Vos points sont doublés.",
        image: "eye.jpg",
        cost: 13,
        max: 1,
    },
    unknow: {
        id: "unknow",
        name: "Some cloud...",
        description: "whoever read this love adolph hitler",
        image: "unknow.jpg",
        cost: 88,
        max: 1,
    },
};
