"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.powers = void 0;
exports.powers = {
    lucien: {
        id: "lucien",
        name: "Lucien",
        description: "power_lucien",
        image: "lucien.jpg",
        cost: 0,
        max: 3,
    },
    phone: {
        id: "phone",
        name: "Gramophone",
        description: "power_phone",
        image: "phone.jpg",
        cost: 4,
        max: 3,
    },
    fox: {
        id: "fox",
        name: "Jackson Gambler",
        description: "power_fox",
        image: "fox.jpg",
        cost: 5,
        max: 3,
    },
    deserterJack: {
        id: "deserterJack",
        name: "Deserter Jack",
        description: "power_deserterJack",
        image: "leave.jpg",
        cost: 8,
        max: 3,
    },
    monkeys: {
        id: "monkeys",
        name: "Smart monkeys",
        description: "power_monkeys",
        image: "monkeys.jpg",
        cost: 11,
        max: 3,
    },
    mirror: {
        id: "mirror",
        name: "Mirror of Darkness",
        description: "power_mirror",
        image: "mirror.jpg",
        cost: 7,
        max: 1,
    },
    steve: {
        id: "steve",
        name: "Hurry Steve",
        description: "power_steve",
        image: "first.jpg",
        cost: 9,
        max: 3,
    },
    pact: {
        id: "pact",
        name: "War pact",
        description: "power_pact",
        image: "pact.jpg",
        cost: 5,
        max: 3,
    },
    watch: {
        id: "watch",
        name: "Early Fang",
        description: "power_watch",
        image: "watch.jpg",
        cost: 10,
        max: 3,
    },
    chimist: {
        id: "chimist",
        name: "Stacy Chemistry",
        description: "power_chimist",
        image: "chimist.jpg",
        cost: 18,
        max: 1,
    },
    fog: {
        id: "fog",
        name: "Fog of war",
        description: "power_fog",
        image: "fog.jpg",
        cost: 16,
        max: 1,
    },
    curse: {
        id: "curse",
        name: "Emma Curse",
        description: "power_curse",
        image: "curse.jpg",
        cost: 16,
        max: 3,
    },
    final: {
        id: "final",
        name: "Let's do it",
        description: "power_final",
        image: "final.jpg",
        cost: 32,
        max: 1,
    },
    karen: {
        id: "karen",
        name: "Complain Karen",
        description: "power_karen",
        image: "karen.jpg",
        cost: 30,
        max: 1,
    },
    eye: {
        id: "eye",
        name: "Eye of the god",
        description: "power_eye",
        image: "eye.jpg",
        cost: 13,
        max: 1,
    },
    unknow: {
        id: "unknow",
        name: "Some cloud...",
        description: "power_unknow",
        image: "unknow.jpg",
        cost: 88,
        max: 1,
    },
};
